# SQL Interview Questions  - Quiz

## Introduction

In this lesson, we'll go through a short quiz containing the types of questions about SQL and relational databases that you can expect to see in an interview. 



## SQL Interview Questions

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

what are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line:
_______________________________________________________________________________________________________________________________

text, blob, integer, real



## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
_______________________________________________________________________________________________________________________________

a primary key is a column in a table and a foreign key is used to join two tables together



## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________

one-to-one

two tables where both tables are associated using one row 

one-to-many

this is when the first table's primary key matches with multiple foreign keys in the second table

many-to-many

usually reuires a joining table as multiple items in the first table match with multiple in the second. for instance, multiple people have been to multiple concerts and multiple concerts have had multiple people attend


## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________

inner, outer, left, right.

Inner joins everything in the right table that matches the records of the left table

Outer joins everything regardless of matching between tables

left joins everything form the right table that matches on the left table

right joins everything from the left table that matches on the right table


## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:
_______________________________________________________________________________________________________________________________

aggregate functions perform calculations on a column
group by groups specific rows together


## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:
_______________________________________________________________________________________________________________________________

Associative entities act as the joining table, referencing items in both tables being joined. for instance the musicians in a band and the bands on a concert tour. the concert tour has multiple bands and each band has multiple people, 


## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.